stages:
  data_ingestion:
    cmd: uv run src/data/data_ingestion.py
    deps:
    - src/data/data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - data/raw/train.csv
    - data/raw/test.csv
  
  data_preprocessing:
    cmd: uv run src/data/data_preprocessing.py
    deps: 
    - data/raw/train.csv
    - data/raw/test.csv
    outs:
    - data/interim/train_processed.csv
    - data/interim/test_processed.csv
  
  model_building:
    cmd: uv run src/model/model_building.py
    deps:
    - src/data/data_preprocessing.py
    - data/interim/train_processed.csv
    - src/model/model_building.py
    params:
    - model_building.max_features
    - model_building.ngram_range
    - model_building.learning_rate
    - model_building.max_depth
    - model_building.n_estimators
    outs:
    - lgbm_model.pkl
    - tfidf_vectorizer.pkl

  model_evaluation:
    cmd: uv run src/model/model_evaluation.py
    deps:
    - src/model/model_building.py
    - lgbm_model.pkl
    - tfidf_vectorizer.pkl
    outs:
    - experiment_info.json
  
  model_registration:
    cmd: python src/model/register_model.py
    deps:
    - experiment_info.json
    - src/model/register_model.py