stages:
  data_ingestion:
    cmd: uv run src/data/data_ingestion.py
    deps:
    - src/data/data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - data/raw/train.csv
    - data/raw/test.csv
  
  data_preprocessing:
    cmd: uv run src/data/data_preprocessing.py
    deps: 
    - data/raw/train.csv
    - data/raw/test.csv
    outs:
    - data/interim/train_processed.csv
    - data/interim/test_processed.csv